### ISSUE TITLE
Publish to Maven Central since Bintray decommissioned

### ISSUE THREAD

**Issue by tommyli** [genepi/genepi-libs#4]
Due to [sunsetting of Bintray](https://bintray.com/), genepi-libs are no longer available to dependency management tools such as Maven or Gradle.  Are there any plans to move these to [Maven Central](https://maven.apache.org/repository/)?

If so then great, I'm happy to help on that.

If not then can I request permission to publish these libs to Maven Central?

**Comment by lukfor** [comment]
Thank you. Our libraries are now available in the following repository:
```
<repositories>
	<repository>
		<id>jfrog-genepi-maven</id>
		<name>jfrog-genepi-maven</name>
		<url>https://genepi.jfrog.io/artifactory/maven/</url>
	</repository>
</repositories>
```

I updated the README.

**Comment by tommyli** [comment]
Thank you, our build is passing again, thanks.
